name: Infrastructure Monitoring Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Disk Space Monitoring
        run: |
          df -h
          DISK_USAGE=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
          if [ "$DISK_USAGE" -ge 80 ]; then
            echo "Disk usage is at $DISK_USAGE%. Alert: Disk space is low!"
            exit 1
          else
            echo "Disk usage is at $DISK_USAGE%. Everything is fine."
          fi

      - name: Check Service Uptime
        if: false
        run: |
          EXTERNAL_IP="202.191.100.101"
           PORT="80"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "http://$EXTERNAL_IP:$PORT")
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Service is down with status code $STATUS_CODE."
            exit 1
          else
            echo "Service is up and running at $EXTERNAL_IP."
          fi

      - name: Parse Logs for Errors
        run: |
          LOG_FILE="application.log"
          if grep -i "error" "$LOG_FILE"; then
            echo "Errors found in the logs:"
            grep -i "error" "$LOG_FILE"
            exit 1
          else
            echo "No errors found in the logs."
          fi

      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Monitoring Workflow Failed!"
          body: |
            Hello,

            The GitHub Actions monitoring workflow has failed. Please review the logs to address the issue.

            - Workflow: Infrastructure Monitoring Workflow
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Time: ${{ github.run_started_at }}

            Regards,
            DevOps Team
          to: lehaidat123@gmail.com
          from: monitoring@example.com
